### PR TITLE
Discuss: Removal of BOARD_HAVE_PIXEL_FORMAT_INFO

### PR DESCRIPTION
**Pull request by tetsuo55**
It is not possible to open a ticket in this repo so i am doing this as a pull request.

This config option does not exist in AOSP and has not been pulled in again for CM13.
The commit that added the code says its a hack for webkit.

I think everything should work without this.
If you can confirm my findings then we can remove both this line and revert this commit https://github.com/timduru/platform-frameworks-native/commit/f52a2d947b597236aa875afd7b41a7c58b227c8b

### CODE REVIEW

**Comment by timduru** [comment]
it's needed for the video libs.

**Comment by tetsuo55** [comment]
Are you sure? because its not used on CM and presumably video works?

**Comment by timduru** [comment]
Yes: 
 strings hwcomposer.tegra.so |grep PixelFormatInfo
_ZN7android18getPixelFormatInfoEiPNS_15PixelFormatInfoE

I don't think CM has a working TF version ?

**Comment by tetsuo55** [comment]
maybe it's because cm has this: https://github.com/CyanogenMod/android_device_asus_tf300t/tree/cm-13.0/libcardhuu

**Comment by timduru** [comment]
yes, you can inject it in a separate lib.
It was just easier to simply restore the commit in katkiss.

**Comment by tetsuo55** [comment]
ok I will come back to that (much) later

**Pull request closed without merging**
